### ISSUE TITLE
Removal of dependencies for documentations

### ISSUE THREAD

**Issue by WillemWybo** [unibe-cns/NEAT#116]
Is it possible to remove the requirements for 
```
# documentation
sphinx>=2.4.3
nbsphinx>=0.5.1
sphinx-gallery>=0.7
```
from the main requirements file?

**Comment by jakobj** [comment]
do you mean like this: https://github.com/Happy-Algorithms-League/hal-cgp/blob/master/extra-requirements.txt ?

**Comment by WillemWybo** [comment]
Perhaps, what does it do?

**Comment by jakobj** [comment]
it's read by our `setup.py` and specifies optional requirements https://github.com/Happy-Algorithms-League/hal-cgp/blob/master/setup.py#L74 for example sphinx

**Comment by WillemWybo** [comment]
Ah I see, that could work.

**Comment by benelot** [comment]
@jakobj And what does it do with the optional requirements?

@WillemWybo Yes, these requirements can be removed as they are required for sphinx doc, for which we actually have a separate doc.txt in the requirements folder.

**Comment by jakobj** [comment]
> @jakobj And what does it do with the optional requirements?

you can use them in `setup.py`
```python
setup(
    [...]
    extras_require={'doc': <stuff>},
    [...]
```
and it give you an installation target, for pip: `pip install <my library>[doc]`
