### ISSUE TITLE
Figure scaling in docs/index.rst

### ISSUE THREAD

**Issue by WillemWybo** [unibe-cns/NEAT#42]
I've made some figures to explain the structure of NEAT (they are in my pull request). Added them to `docs/index.rst` but the scaling is hardcoded, would be nice to automatically have the width adjusted to the page width and height scaled accordingly.

**Comment by benelot** [comment]
@WillemWybo Is this considered done so far?

**Comment by WillemWybo** [comment]
I haven't looked into this. In particular figure 1 is a bit small now
