### ISSUE TITLE
Assigne cores based on number of `_calcFitMatrices` calls in `CompartmentFitter`

### ISSUE THREAD

**Issue by WillemWybo** [unibe-cns/NEAT#56]
`CompartmentFitter` should assign cores for each ion channel based on number of `_calcFitMatrices` calls, or equivalently the length of the lists returned by `getExpansionPoints()`

**Comment by WillemWybo** [comment]
This one is solved right? @jakobj

**Comment by jakobj** [comment]
no, not that i'm aware of. i haven't worked on an implementation of this feature, so i think the assignment is still made ignoring the number of calls.

**Comment by WillemWybo** [comment]
Deprecated
