### ISSUE TITLE
Reduce version of sphinx-gallery?

### ISSUE THREAD

**Issue by jakobj** [unibe-cns/NEAT#66]
my pip can't find it: `ERROR: Could not find a version that satisfies the requirement sphinx-gallery>=0.7 (from neat==0.9) (from versions: 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.10, 0.0.11.post1, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.1.10, 0.1.11, 0.1.12, 0.1.13, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 0.5.0, 0.6.0, 0.6.1)
ERROR: No matching distribution found for sphinx-gallery>=0.7 (from neat==0.9)`

@benelot

**Comment by benelot** [comment]
We could actually remove the sphinx-gallery for now altogether. It is meant to show some overview of different examples such as the front page of scikit-learn: https://scikit-learn.org/stable/index.html

Do we want something like this soon? @WillemWybo @jakobj

**Comment by WillemWybo** [comment]
Sure!

**Comment by benelot** [comment]
Ok, I will drop the dependency and we can add it again later on if we want the gallery.
