### ISSUE TITLE
Missing docstrings on website

### ISSUE THREAD

**Issue by WillemWybo** [unibe-cns/NEAT#83]
e.g. of `GreensTree.setImpedance`

**Comment by benelot** [comment]
On master is no docstring for setImpedance?

**Comment by benelot** [comment]
https://github.com/unibe-cns/NEAT/blob/master/neat/trees/greenstree.py

**Comment by WillemWybo** [comment]
Line 271. Note that this is on the website that I build locally on my machine (on the public one all docstrings are missing)

**Comment by benelot** [comment]
Hmm weird, yesterday, it had no docstring!

**Comment by benelot** [comment]
Ok, weird, I will look into it.

**Comment by WillemWybo** [comment]
There might be other functions with a similar name. For instance `_setImpedance()` has no docstring.

**Comment by benelot** [comment]
That was probably the one I saw.

**Comment by benelot** [comment]
Duplicate of #86. I will close this for now, and fix it together with #86 . Please reopen if the problem persists after fixing the other one.

**Comment by WillemWybo** [comment]
Are you sure #86 and #83 they have the same cause?

**Comment by benelot** [comment]
I am now sure that it does not have the same cause.
