### ISSUE TITLE
Fix `IonChannel` docstring

### ISSUE THREAD

**Issue by WillemWybo** [unibe-cns/NEAT#84]
Some greek symbols don't render, fractions don't render and there are (possibly related) layout issues with the docstring of `neat.IonChannel`

**Comment by benelot** [comment]
The problem with the symbols is that the backslash is already applied at the python stage, not the sphinx stage, therefore it tries to find a special \a and a special \b character, which it can not find. To get alpha and beta, just use double backslashes: \\alpha and \\beta. It is just weird that it worked for other situations such as \overline, where the same problem should apply but doesn't. Weird world.

Source: http://openalea.gforge.inria.fr/doc/openalea/doc/_build/html/source/sphinx/rest_syntax.html#text-syntax-bold-italic-verbatim-and-special-characters

**Comment by benelot** [comment]
I am just waiting for the docs build to pass, then we can close this. Sorry for not pull-requesting, but the improvement is just way harder to do without directly committing to master

**Comment by benelot** [comment]
Looks like they are all fine now: https://neatdend.readthedocs.io/en/latest/reference/trees.html#defining-ion-channels

I had to hardrefresh in my browser to skip caching and get the new page from the server, but that is just because I just loaded the page again.
