### ISSUE TITLE
Example gallery for website

### ISSUE THREAD

**Issue by WillemWybo** [unibe-cns/NEAT#85]
I added a directory `examples/` to the root package directory, with three example scripts. I also added three figures to `docs/figures`. It would be nice if we could put those figures on the website under the 'Examples' tab (maybe below 'Tutorials'). Clicking on those figures could then link to the associated scripts on the github?

**Comment by benelot** [comment]
Sounds doable, I will propose a first version.

**Comment by WillemWybo** [comment]
Great!

**Comment by benelot** [comment]
First version proposed, check out Examples
