### ISSUE TITLE
Can not install properly

### ISSUE THREAD

**Issue by sunzhenyang2018** [unibe-cns/NEAT#91]
Hi,

I installed everything in requirement.txt already, and then used "python setup.py install"
I encountered a bug where a lot of syntax errors were encountered in NETC.cc, which I fixed by changing all "and" and "or" to "&&" and "||". After fixing that, I encountered the issue in the picture. 

(The two pictures are the complete output from "python setup.py install" to when installation was halted by some error)

![issue1](https://user-images.githubusercontent.com/65326026/87865919-c856d080-c92f-11ea-978e-e30406d2efe4.JPG)
![issue2](https://user-images.githubusercontent.com/65326026/87865923-cee54800-c92f-11ea-84c3-bfa903f10992.JPG)

**Comment by WillemWybo** [comment]
Thanks for raising this issue! I have fixed the errors you are seeing with this pull request: [https://github.com/unibe-cns/NEAT/pull/92](url)

Probably your compiler has a different level of 'strictness' to the one(s) we used causing the error.

**Comment by WillemWybo** [comment]
Thanks for the remark on the usage of "&&" and "||", I was not aware of it but it is recommended apparently [https://stackoverflow.com/questions/4251699/is-it-okay-to-use-and-or-etc-instead-of](url), and hence we should adopt it. You are welcome to create a pull request with your correction.

**Comment by sunzhenyang2018** [comment]
I was able to install without error after your fix. Thank you. Also, I have created a pull request where "&&" and "||" are used instead of "and" and "||".

**Comment by WillemWybo** [comment]
Many thanks for the PR
